### PR TITLE
Minor fix: Update links from Institution to InstServer

### PR DESCRIPTION
**Pull request by vladimir-mencl-eresearch**
Update code linking from Institution to InstServer to reflect changes in the
model introduced in 15691d3 - instead of instserver_set, use the relation name
"servers" now explicitly given in the model.

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
... and just as explanation, the reason for making this fix is I was getting:

```
AttributeError: 'Institution' object has no attribute 'instserver_set'
```

from either `./manage.py servdata` or from the `/radius_serv_data` URL when uncommented.

**Comment by zmousm** [comment]
I am afraid the InstServer M2M patch was merged by (git-spaghetti-merge) mistake :( I am saying this because I asked for this but it's (unfortunately) still in my queue for testing and fine-tuning, so the patch is almost certainly not complete. So it is quite likely there are more issues besides the ones you spotted in this PR and attended to in REANNZ@4445bc0659e0a9f5e597b0fe24cc63acc30c8bf4, REANNZ@dc4667e01b9a2e36a0d5fa720319b501fafcdd35 . I am terribly sorry about this mess and the inconvenience it may have caused. We are surely moving forward with the InstServer change but it will take me a few (more) days to test the original patch and return to all the outstanding issues. As for the other commits, I may suggest that you submit them separately from this PR.

**Comment by vladimir-mencl-eresearch** [comment]
Hi Zenon,

I understand how this can happen.

I have not done a full coverage test - if you have a patch that you'd be merging in, I'm happy to wait.

Btw, should I create a separate pull-request cherry-picking the other wtwo fixes - 5aafd60 and e26e46d ?

Cheers,
Vladimir

**Comment by vladimir-mencl-eresearch** [comment]
Hi Zenon,

I have moved the two fixes unrelated to the InstServer M2M change into #10 - and I'll wait for you to merge the broader InstServer M2M patch you were referring to.  And so I will close this PR now....

I look forward to hearing from you soon.

Cheers,
Vlad
